// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"

import domain "github.com/andrefebrianto/URL-Shortener-Service/src/model"
import mock "github.com/stretchr/testify/mock"

// ShortLinkUsecase is an autogenerated mock type for the ShortLinkUsecase type
type ShortLinkUsecase struct {
	mock.Mock
}

// AddCounterByCode provides a mock function with given fields: ctx, code, counter
func (_m *ShortLinkUsecase) AddCounterByCode(ctx context.Context, code string, counter uint64) error {
	ret := _m.Called(ctx, code, counter)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, uint64) error); ok {
		r0 = rf(ctx, code, counter)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Create provides a mock function with given fields: ctx, shortlink
func (_m *ShortLinkUsecase) Create(ctx context.Context, shortlink *domain.ShortLink) error {
	ret := _m.Called(ctx, shortlink)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.ShortLink) error); ok {
		r0 = rf(ctx, shortlink)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteByCode provides a mock function with given fields: ctx, code
func (_m *ShortLinkUsecase) DeleteByCode(ctx context.Context, code string) error {
	ret := _m.Called(ctx, code)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, code)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields: ctx
func (_m *ShortLinkUsecase) GetAll(ctx context.Context) ([]domain.ShortLink, error) {
	ret := _m.Called(ctx)

	var r0 []domain.ShortLink
	if rf, ok := ret.Get(0).(func(context.Context) []domain.ShortLink); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ShortLink)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByCode provides a mock function with given fields: ctx, code
func (_m *ShortLinkUsecase) GetByCode(ctx context.Context, code string) (*domain.ShortLink, error) {
	ret := _m.Called(ctx, code)

	var r0 *domain.ShortLink
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.ShortLink); ok {
		r0 = rf(ctx, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ShortLink)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateByCode provides a mock function with given fields: ctx, shortlink
func (_m *ShortLinkUsecase) UpdateByCode(ctx context.Context, shortlink *domain.ShortLink) error {
	ret := _m.Called(ctx, shortlink)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.ShortLink) error); ok {
		r0 = rf(ctx, shortlink)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
